### ISSUE TITLE
Generated Java code fails with SAXParseException:  'http' access is not allowed due to restriction set by the accessExternalDTD property

### ISSUE THREAD

**Issue by gnewton** [gnewton/chidley#9]
[org.xml.sax.SAXParseException; systemId: file:/home/gnewton/gocode/src/github.com/gnewton/chidley/xml/ActorPreludeSample.xml; lineNumber: 2; columnNumber: 123; External DTD: Failed to read external DTD 'partwise.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.]

**Comment by gnewton** [comment]
Issue fixed: new Exception:
`Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.musicxml.org/dtds/partwise.dtd`

**Comment by gnewton** [comment]
Exception is only for some dtd urls. Think some http daemons set up to reject user agents that do not look like browsers. Fixed with:

`System.setProperty("http.agent", "Mozilla/5.0 (X11; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0");`

**Comment by gnewton** [comment]
merged in to master

**Comment by malavancs** [comment]
Can you share how did you resolve this ?
[org.xml.sax.SAXParseException; systemId: file:/home/gnewton/gocode/src/github.com/gnewton/chidley/xml/ActorPreludeSample.xml; lineNumber: 2; columnNumber: 123; External DTD: Failed to read external DTD 'partwise.dtd', because 'http' access is not allowed due to restriction set by the accessExternalDTD property.]
